[main]
include=~/.config/foot/themes/theme
# font = JetBrainsMonoNerdFont:size=12
font = Comic Mono:size=16
pad = 6x6 center

[tweak]
font-monospace-warn=no
pad = 6x6 center

[colors-dark]
# 0.8
alpha = 1.0
blur=yes
